root            : /Users/lukasvandenheuvel/Documents/PhD/Data-temp/20240718_1B_sarkosyl/20240815_Titan3
path_to_star    : /Users/lukasvandenheuvel/Documents/PhD/Data-temp/20240718_1B_sarkosyl/CStoRelion/cs2star_J194/particles_test.star

rescale         : 0.125
sigma_view      : 10
sigma_background : 200

# Ridge detection
dog_sigmas      : [40,50,60]        # low sigma for DoG in angstroms. Should be roughly the radius of the fibril
ridge_threshold : -0.25
min_length_skel : 200        # Minimal fibril length in angstrom for skeletonization

# Hough transform
hough_line_length : 60
hough_line_gap    : 17

# Line pruning
max_angle         : 10
max_distance      : 60
min_length        : 350

# Ellipse convolution
ellipse_kernel_size : 350 # kernel size
ellipse_radius      : 60 # fibril radius
ellipse_theta       : 10  # angle step. 180 / ellipse_theta must yield and integer

# Remove fibrils based on FFT
check_helix_fft     : True
num_freq_bins       : 150
butterfilter_order  : 4
butterfilter_cutoff : 0.25 # Relative cutoff frequency, must not exceed 0.5 (nyquist)
peak_prominence     : 0.03 # Increasing will result in detecting less peaks
helical_rise_range  : [4.6,5.0]

# Remove detections parallel to the edges (they usually correspond to artifacts)
edge_percentage     : 0.1

# Only keep micrographs with more than xx fibril particles
min_num_fibrils     : 2

# In case of local fibril extraction (based on pre-existing SPA coordinates)
fibril_length       : 600 # Fibril length to extract in A