root            : /mnt/em_data/lukas/1B_sarkosyl
path_to_micrographs_star : /MotionCorr/job017/corrected_micrographs.star

rescale         : 0.125
sigma_view      : 10
sigma_background : 200

# Ridge detection
dog_sigmas      : [40,50,60]        # low sigma for DoG in angstroms. Should be roughly the radius of the fibril
ridge_threshold : -0.25
min_length_skel : 200        # Minimal fibril length in angstrom for skeletonization

# Hough transform
hough_line_length : 60
hough_line_gap    : 17

# Line pruning
max_angle         : 10
max_distance      : 60
min_length        : 350

# Ellipse convolution
ellipse_kernel_size : 400 # kernel size
ellipse_radius      : 50  # fibril radius
ellipse_theta       : 10  # angle step. 180 / ellipse_theta must yield and integer

edge_percentage     : 0.1
